<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>

<table class="table">
<tr>
    <th>time</th>
    <th>type</th>
    <th>category</th>
</tr>
<?php foreach ($albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->time);?></td>
    <td><?php echo $this->escapeHtml($album->type);?></td>
    <td><?php echo $this->escapeHtml($album->not_or_war);?></td>
</tr>
<?php endforeach; ?>
</table>